-- CreateEnum
CREATE TYPE "Vibe" AS ENUM ('DATING', 'FRIENDS', 'FAMILY', 'SOLO', 'STREET_FOOD', 'BUDGET_EATS', 'PREMIUM_DINING', 'LOCAL_AUTHENTIC', 'MUSIC', 'QUIET', 'ROMANTIC', 'LATE_NIGHT', 'SIGHTSEEING', 'INSTAGRAM_WORTHY', 'NATURE', 'CITY_VIEW', 'HIDDEN_GEM', 'UNDER_100', 'STUDENT_FRIENDLY', 'QUICK_BITE');

-- AlterTable
ALTER TABLE "Post" ADD COLUMN     "vibes" "Vibe"[];
